### PR TITLE
Parse thread proc files

### PR DESCRIPTION
**Pull request by overvenus**
Export parsing proc fiels, so we can get thread information, `/proc/[pid]/task/[tid]/...`.

### CODE REVIEW

**Comment by danburkert** [comment]
I haven't needed to use the APIs on a specific thread before so I might be way off, but can't you substitute the tid for the pid since they are they same on linux?  E.g. instead of using `/proc/5/task/6/...`, just use `/proc/6/...`?

**Comment by overvenus** [comment]
They are actually different. `/proc/6/...` is process scope and `/proc/5/task/6/...` is thread scope.
Eg,

```
[pingcap@ip-172-16-30-6 21633]$ cat /proc/21795/stat
21795 (raftstore-1) R 1 21633 21633 0 -1 4202560 17624048 429 0 0 166002 54355 0 2 20 0 269 0 1754026370 6414716928 869598 18446744073709551615 94544665092096 94544685097907 140732154529680 139772137806048 140732154894018 0 0 4096 20035 18446744073709551615 0 0 -1 34 0 0 0 0 0 94544687195552 94544688053968 94544696508416 140732154531390 140732154531586 140732154531586 140732154531797 0
[pingcap@ip-172-16-30-6 21633]$ cat /proc/21633/task/21795/stat
21795 (raftstore-1) R 1 21633 21633 0 -1 1077944384 24163 429 0 0 9290 2864 0 2 20 0 269 0 1754026370 6414716928 870330 18446744073709551615 94544665092096 94544685097907 140732154529680 139772137806048 139774340318410 0 0 4096 20035 18446744071579856438 0 0 -1 11 0 0 0 0 0 94544687195552 94544688053968 94544696508416 140732154531390 140732154531586 140732154531586 140732154531797 0
```

**Comment by danburkert** [comment]
ah, interesting.  What do you think about exposing these as variants that take a pid and tid, instead of the file handle, e.g.

```rust
 /// Returns resource limit information from the thread with the provided parent process ID and thread ID.
 pub fn limits_task(process_id: pid_t, thread_id: pid_t) -> Result<Limits> {
     limits_file(&mut try!(File::open(&format!("/proc/{}/task/{}/limits", process_id, thread_id))))
 }
```

**Comment by overvenus** [comment]
Comment addressed, PTAL

**Comment by danburkert** [comment]
Thanks!

**Pull request merged**
